services:
  - type: web
    name: comexiger-pruebas
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT COMEXIGER.asgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "comexiger-pruebas.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://comexiger-pruebas.onrender.com"
